on: 
  schedule:
    - cron: '* * * * *'
    
name: "Verify events"

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Verify events
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://calendar-io.vercel.app/api/events/send-notification'
        method: 'GET'
